//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela
    {
        public int TabelaID { get; set; }
        public int TimID { get; set; }
        public Nullable<int> BrojPobjeda { get; set; }
        public Nullable<int> BrojPoraza { get; set; }
        public Nullable<int> BrojNerjesenih { get; set; }
        public Nullable<int> GolRazlika { get; set; }
        public Nullable<int> BrojBodova { get; set; }
    
        public virtual Tim Tim { get; set; }
    }
}
