//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucinak
    {
        public int IgracID { get; set; }
        public int UtakmicaID { get; set; }
        public int OdigranihMinuta { get; set; }
        public int Golova { get; set; }
        public int ZutihKartona { get; set; }
        public int CrvenihKartona { get; set; }
        public int UcinakID { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Utakmica Utakmica { get; set; }
    }
}
